#4 - Database schema for auth system
Bitten-Code-Projects/GameSync.Api pull request #3
Opened 2024-11-24 16:46 UTC by DTroczyk

# What

I’m adding the default DbContext named AppDbContext along with ASP.NET Identity configuration. The default Identity user has been extended with an additional field, LastIP.

Default ASP.NET Identity endpoints have been added under the account/... URL.

# Why

This task comes from Trello. The requirement is to use ASP.NET Identity.

# Chengelog

## Added
- ApplicationUser, which extends IdentityUser with the LastIP property.
- Default context named AppDbContext, implementing the ASP.NET Identity context.
- Authentication configuration for Swagger.
- AppDbContextFactory, necessary for creating migrations.
-I nitial migration with Identity models.

## Deprecated

- ExampleDbContext.

## Removed

- Example migration files.

2024-11-24 16:49 UTC, DTroczyk commented
![](https://github.trello.services/images/mini-trello-icon.png) [Database schema for auth system](https://trello.com/c/NO9eyfNW/4-database-schema-for-auth-system)

2024-11-27 15:21 UTC, PanKunik requested changes
And we have got a runtime exception:
`fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
      An unhandled exception has occurred while executing the request.`

You need to delete `IRequest<T>` implementations, because we don't have the handlers for them.

2024-12-15 16:42 UTC, ogendogen reviewed
Let's discuss about comments on weekly

2024-12-15 16:42 UTC, ogendogen commented on GameSync.Infrastructure/Context/AppDbContext.cs
> +            string connString = Environment.GetEnvironmentVariable("gameSyncConnString") ??
Change name style of environment variable to something like `GAMESYNC_CONNECTIONSTRING`

2024-12-15 16:42 UTC, ogendogen commented on GameSync.Infrastructure/Context/AppDbContext.cs
> +            string connString = Environment.GetEnvironmentVariable("gameSyncConnString") ??
In my opinion it can stay like it until we agree on common docker compose infrastructure for development

2024-12-15 16:42 UTC, ogendogen commented on GameSync.Infrastructure/Context/AppDbContext.cs
> +    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
Isn't it required by base DbContext class?

2024-12-15 16:42 UTC, ogendogen commented on GameSync.Infrastructure/Context/AppDbContextFactory.cs
> +                            "server=127.0.0.1;database=GameSync;user=root;password=example;";
Change name style of environment variable to something like `GAMESYNC_CONNECTIONSTRING`

2024-12-15 16:42 UTC, ogendogen commented on GameSync.Infrastructure/Context/AppDbContext.cs
> +    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
Got it now, seems like doubled code. Let's discuss it on weekly

2024-12-15 16:42 UTC, ogendogen commented on GameSync.Infrastructure/Migrations/20241124144330_InitialMigrationWithIdentity.cs
> +﻿using System;
Since it's autogenerated code, the following answer might be suitable for this case https://stackoverflow.com/a/27149879

2025-01-06 10:53 UTC, DTroczyk commented on GameSync.Infrastructure/Context/AppDbContext.cs
> +    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
The factory method is necessary to create migrations because the `dotnet ef` tool doesn't have access to the configuration in `Program.cs`.

I don't remember why, but if I remove the factory or the `OnConfiguring` method, creating migrations doesn't work.

2025-01-06 10:56 UTC, DTroczyk commented on GameSync.Infrastructure/Context/AppDbContext.cs
> +            string connString = Environment.GetEnvironmentVariable("gameSyncConnString") ??
Changed

2025-01-06 10:56 UTC, DTroczyk commented on GameSync.Infrastructure/Context/AppDbContextFactory.cs
> +                            "server=127.0.0.1;database=GameSync;user=root;password=example;";
Changed

2025-01-06 11:04 UTC, DTroczyk commented on GameSync.Infrastructure/Migrations/20241124144330_InitialMigrationWithIdentity.cs
> +﻿using System;
I added the line `// <auto-generated />` at the top to ignore this file.

2025-01-07 19:37 UTC, ogendogen approved these changes

2025-01-07 19:38 UTC, Linky141 approved these changes

2025-01-08 14:51 UTC, PanKunik approved these changes

2025-01-08 17:02 UTC, merged